---
title: "r code hw"
author: "h24089014"
date: "2020/5/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

r code 整理 h24089014 許祐誠

************************************** Theme1 - Common operations **************************************

1. Basic operations
```{r}
1+2   ##加法
1-5   ##減法
1*8   ##乘法
9/3   ##除法
```


2.Power, square root
```{r}
5^3   ##5的3次方 (1)
5**5  ##2的3次方 (2)
sqrt(144) ## 144 的開平方根
```


3.Quotient and remainder
```{r}
13%%5    ##13除以5的餘數
13%/%5   ##13除以5的商數
```

4.Take the absolute value
```{r}
abs(-11523) #-11523的絕對值
```

5.take log & exponential
```{r}
log(123)   ##對123取log
exp(123)   ##對123取exponential
```


************************************** Theme 2 - variable & data **************************************

1.Variable
```{r}
x<-123456789  ##指定x為某數
y<-log(456)+exp(5) ##指定y為某函數

#########對x & y 做四則運算#########

x+y
x-y
x*y
x/y  

```

2.vector
```{r}
x<-c(a=123,b=456,c=789)  ##創造一個元素為123,456,789的向量
x                        ##回傳x
 
x[2]                     ##回傳第二元素的所有訊息(包含名稱及值)
x[[2]]                   ##回傳第二元素的值

 
```

3.sequence
```{r}
1:124         #創造一個1~124的數列(1)
seq(1,124)    #創造一個1~124的數列(2)
seq(1,124,12) #創造一個1~124的數列,間隔為12
rep((1:3),3)  #重複(1,2,3)向量3次

#####向量運算#####
x<-c(1,2,3)
y<-c(4,5,6)
#向量四則運算#
x+y
x-y
x/y
x*y
#其他向量運算#
sum(c(123,456,789)) ##對此向量所有元素做加總
prod(c(123,456,789))##對此向量所有元素做乘積
sort(c(123,456,789))##對向量中元素由大排到小
rank(c(123,456,789))##對向量中元素給予由小到大的rank
``` 
4.matrix
```{r}
matrix(c(1:9), nrow = 3, ncol = 3) ##按照 column 創造矩陣
matrix(c(1:4), nrow = 2, ncol = 2, byrow = TRUE) ##按照 row 創造矩陣


##利用向量創造矩陣##
x<-c(123,456,789)
y<-c(111,222,333)
z<-c(0,1,2)
rbind(x,y,z) ##按照row排序成一個矩陣
cbind(x,y,z) ##按照column排序成一個矩陣

##計算行列式值以及找出對角線元素
a<-cbind(x,y,z)
det(a)     ##計算行列式值
diag(a)    ##找出對角線元素

##為矩陣行&列命名
```


```{r}
colnames(a) <- c("c1", "c2", "c3")
rownames(a) <- c("r1", "r3" , "r3")
colnames(a)
rownames(a)
```

5.list
```{r}
x<- list(a = 123, b = TRUE, c = "我要歐趴", d = c(123, 456, 789))
x
x[1]  ##找list中第一個元素
x$a   ##找list中名稱為a的元素
```


************************************** Theme3 - Control flow **************************************

1.Logical judgment
```{r}
x<-123
y<-456
x>125
!(x>125)
y<455
!(y>455)
x>125&y<455
```

2.Conditional execution
```{r}
##if else    
x<-123

##簡單的邏輯:如果x大於120則令y為456，否則令為789
if(123>120) {
  y<-456
}else{
  y<-789
}
y
```
```{r}
##if else if else
x<-123
##上述if else 之單行寫法
y<-ifelse(x>120,456,789)
y
```

3.Loop structure
```{r}
##for迴圈
x<-0
for(x in c(1:10)) {
  y<-x*y
}
y

##while迴圈
x<-1
y<-0
while(x<=10){
  y=x+y
  x=x+1
}
x
y
```